# Build and run unit tests
name: CI

on: [ push, pull_request ]

jobs:
  main:
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-18.04, macOS-10.15, windows-2019 ]
        dc: [ ldc-master, ldc-latest, ldc-1.20.0, dmd-latest, dmd-2.090.1 ]
        exclude:
          # https://github.com/dlang/dub/issues/1914
          # https://github.com/dlang/dub/issues/1915
          - { os: windows-2019, dc: dmd-latest }
          - { os: windows-2019, dc: dmd-2.090.1 }

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
    - uses: dlang-community/setup-dlang@v1
      with:
        compiler: ${{ matrix.dc }}

    - name: '[Linux] Install dependencies & setup environment'
      if: runner.os == 'Linux'
      run: |
        sudo apt-get update
        sudo apt-get install libsodium-dev

    - name: '[Windows] Install dependencies'
      if: runner.os == 'Windows' && steps.cache-libsodium.outputs.cache-hit != 'true'
      run: |
        # TODO: Read the version from the base ref
        $url = "https://github.com/jedisct1/libsodium/releases/download/1.0.18-RELEASE/libsodium-1.0.18-msvc.zip"
        $sha256hash = "C1D48D85C9361E350931FFE5067559CD7405A697C655D26955FB568D1084A5F4"
        Write-Host ('Downloading {0} ...' -f $url)
        [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12
        # See https://github.com/PowerShell/PowerShell/issues/2138
        $ProgressPreference = 'SilentlyContinue'
        New-Item -ItemType directory -Path ${{ github.workspace }}\lib\
        Invoke-WebRequest -Uri $url -OutFile '${{ github.workspace }}\lib\libsodium.zip'
        if ((Get-FileHash '${{ github.workspace }}\lib\libsodium.zip' -Algorithm "SHA256").Hash -ne $sha256hash) {
          exit 1
        }
        Expand-Archive '${{ github.workspace }}\lib\libsodium.zip' -DestinationPath '${{ github.workspace }}\lib\'

    - name: 'Build & Test'
      if: runner.os != 'Windows'
      run: |
        dub test --compiler=$DC

    - name: '[Windows] Build & test'
      if: runner.os == 'Windows'
      env:
        LIB: ${{ github.workspace }}\lib\libsodium\x64\Release\v142\static\;$LIB
      shell: cmd
      run: |
        call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
        dub test --compiler=${{ env.DC }}
        if %errorlevel% neq 0 exit /b %errorlevel%

    - name: 'Upload code coverage'
      uses: codecov/codecov-action@v1
      with:
        flags: unittests
